name: CI and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run Test Suite
        run: yarn test
        env:
          CI: true
          FORCE_COLOR: 1

      - name: Create build
        run: yarn build
      
      - uses: darkshredder/web-to-app-action@main
        with:
          build-folder-path: "build" # Defaults to build, It is the folder where build files or html are stored
          app-name: "Covid19India" # Defaults to MyApp
          output-folder-path: "my-apks" # Defaults to apk/, Where final APK files are created
    
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Final-apks
          path: my-apks/ # Should be same as "output-folder-path"
